spring:
  datasource:
    url: ${DATABASE_URL:}
    username: ${DATABASE_USER:}
    password: ${DATABASE_PASSWORD:}
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    schemas: public
    #    repair: true
    baseline-on-migrate: true
    out-of-order: true
    validate-on-migrate: true  # Enable to catch errors
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
springdoc:
  api-docs:
    path: "/apidocs"
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework: INFO
