version: "3.9"
services:
  api:
    container_name: "organic_certification"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_URL
      - FLYWAY_ENABLED
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - organic_network
    volumes:
      - ./application.yaml:/config/application.yaml:ro
  postgres-db:
    image: postgres:latest
    container_name: "postgres-organic"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - organic_network
networks:
  organic_network:
volumes:
  postgres_data:
