version: "3.9"
services:
  api:
    build: .
    container_name: organic_certification
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - postgres-db
    networks:
      - organic_network
    volumes:
      - ./application.yaml:/app/config/application.yaml:ro

  postgres-db:
    image: postgres:latest
    container_name: postgres-organic
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - organic_network

networks:
  organic_network:

volumes:
  postgres_data:
